[project]
name = "bookstore-tabletop-cafe"
version = "0.1.0"
description = "A bookstore/tabletop cafe backend system built with Python FastAPI, SQLAlchemy and PostgreSQL."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4", # Migrations library
    "fastapi[standard]>=0.136.1", # Backend framework
    "psycopg[binary]>=3.3.4", # PostgreSQL database adapter
    "pwdlib[argon2]>=0.3.0", # Password hashing library
    "pyjwt>=2.12.1", # JWT library
    "sqlalchemy>=2.0.49", # ORM library
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.13",
]

[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "migrations",
]


[tool.ruff.lint]
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["F403", "F405"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"