"""Increase isbn length to 20

Revision ID: 38316145004b
Revises: eeb53a825d38
Create Date: 2026-06-09 16:58:48.318652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38316145004b'
down_revision: Union[str, Sequence[str], None] = 'eeb53a825d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###
