"""Make book columns nullable and revert isbn length to 13

Revision ID: 568970493081
Revises: 38316145004b
Create Date: 2026-06-09 17:33:38.674310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '568970493081'
down_revision: Union[str, Sequence[str], None] = '38316145004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=13),
               existing_nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('books', 'pages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'authors',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
               nullable=True)
    op.alter_column('books', 'year_released',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('books', 'synopsis',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'synopsis',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('books', 'year_released',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('books', 'authors',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=255)),
               nullable=False)
    op.alter_column('books', 'pages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
